siteTitle = "Blog by Ben Jongbloedt"
siteDescr = "Thoughts on software and life (but mostly software)."
siteAuthor = "Ben Jongbloedt"

siteTwitterUrl = "https://twitter.com/benjongbloedt"
siteGithubUrl = "https://github.com/bjongbloedt"
siteEmailUrl = "mailto:bjongbloedt@hotmail.com"
siteLinkedinUrl = "https://www.linkedin.com/in/benjongbloedt"
siteStackOverflowUrl = "http://stackoverflow.com/users/7396578/ben-jongbloedt"

googleAnalyticsId = "UA-91794731-1"

linkPrefix = "/gatsby-starter-lumen"
